### PR TITLE
GML-1063: Add list function to datasets

### PR DESCRIPTION
**Pull request by billshitg**

### CODE REVIEW

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/366/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Comment by parkererickson-tg** [comment]
Not sure if this is the way to implement the function... I would have to instantiate an empty Dataset object in order to list the datasets. I know that this is not associated with the DB connection, but a workflow of:

```
conn.listDatasets()
dataset = Dataset("Cora")
conn.ingestDataset(dataset)
```
makes more sense to me than
```
dsList = Dataset()
dsList.listDatasets()
cora = Dataset("Cora")
conn.ingestDataset(cora)
```

Can we have the list dataset function be independent of the dataset object as well as the connection?

**Comment by billshitg** [comment]
Good point. I had the same hesitation while writing it. I also thought about a new function in the datasets module like
`from pyTigerGraph.datasets import listDatasets`, but seems a little weird to import a function to just list the datasets. 

Would this work? If there is no argument to `Dataset()` then print out the available datasets, otherwise, get the dataset.

**Comment by parkererickson-tg** [comment]
Yeah, I see what you're saying. Yeah, I think if you don't initialize the dataset with a specific name then it prints the list makes sense.

**Comment by billshitg** [comment]
Changed to when `Datasets()` is instantiated without name then available datasets will be printed out.

**Review by parkererickson-tg — APPROVED** [review]

**Pull request merged**
