### PR TITLE
Install udf

### PR DESCRIPTION
**Pull request by nzarayeneh**

### CODE REVIEW

**Review by tg-bill — APPROVED** [review]

**Comment by parkererickson** [comment]
I think all is good except missing tests

**Review by parkererickson — CHANGES_REQUESTED** [review]
Looks good except for no tests. Not sure the best way to test this, possibly try to install a query that requires a special UDF and see if that passes?

**Comment by tg-bill** [comment]
This reminds me of one thing: could we add a parameter called something like `force` with initial value false? When it is false, then don't install and print a message like "this will overwrite any existing UDFs. please set force=True to continue". This is to mimic a confirmation dialogue since there is no such thing for the notebook. Or any better way of doing it?

**Comment by parkererickson** [comment]
Not a bad idea. We also need to see how user permissions affect installation. The thing about adding a parameter in a notebook setting is chances are people will just have `conn.installUdf('stuff', force=True)` and then forget to remove that parameter. Not sure how to have it otherwise though

**Comment by parkererickson** [comment]
Makes sense

**Comment by tg-bill** [comment]
@nzarayeneh  does it make sense to you?

**Comment by nzarayeneh** [comment]
> https://docs.tigergraph.com/gsql-ref/current/querying/func/query-user-defined-functions#_define_a_query_udf_in_c

yeah, this makes sense that user get notifies their UDF will gets rewritten. So, should I change it now and add the test as well?

**Comment by tg-bill** [comment]
Let's add the test to finish PR. For better messaging, I think we can do that as a quick follow-up enhancement.

**Review by parkererickson — APPROVED** [review]

**Pull request merged**
