### PR TITLE
Gml 1147 training loop

### PR DESCRIPTION
**Pull request by parkererickson-tg**
To-dos in future PRs:

- Finalize Metrics (add link prediction @k metrics)
- Write NodePiece Built-ins
- Further expand tests
- `.fit()` method in built-in models
- `.predict()` method in trainer and built-in models
- Refactor metrics collection to happen in callbacks
- Update metrics to include multi-class precision/recall, hits@k, recall@k, etc.
- Make heterogeneous graph metadata available as dataloader class attribute
- TQDM support in callbacks
- `filter_by` in dataloaders factory function to accept a list such that it will return multiple dataloaders, one for each filter condition
- clean up logging levels in core functions so that training logs only contain metrics

### CODE REVIEW

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/625/

**Comment by parkererickson-tg** [comment]
@billshitg this failed because of the issue that I was having with PyG when I started working on it. It works with PyG >= 2.2.0.

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/630/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/637/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/639/

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/640/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by billshitg — APPROVED** [review]

**Pull request merged**
