### PR TITLE
Szilard 2022 11b → MultiEdge support

### PR DESCRIPTION
**Pull request by szilardbaranytg**

### CODE REVIEW

**Review by parkererickson-tg — APPROVED** [review]

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/621/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/622/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/624/

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: ABORTED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/627/

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/628/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Pull request merged**
