### PR TITLE
feat(featurizer): add async and thread limit

### PR DESCRIPTION
**Pull request by parkererickson-tg**

### CODE REVIEW

**Review by qe-tigergraph — COMMENTED** [review]
Result: SUCCESS :sunglasses: Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/315/

**Review by billshitg — APPROVED** [review]

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test Result: FAILED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/317/

**Review by qe-tigergraph — COMMENTED** [review]
e2e Test: Skipped Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/317/

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test Result: FAILED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/318/

**Review by qe-tigergraph — COMMENTED** [review]
e2e Test: Skipped Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/318/

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/319/

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/320/

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/322/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/324/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/326/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/327/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/328/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/331/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/333/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/334/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/338/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/339/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/340/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/341/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/342/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/357/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Pull request merged**
