### PR TITLE
fix(featurizer fastrp): fixing attribute error

### PR DESCRIPTION
**Pull request by parkererickson-tg**

### CODE REVIEW

**Review by qe-tigergraph — COMMENTED** [review]
Result: SUCCESS :sunglasses: Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/268/

**Review by qe-tigergraph — COMMENTED** [review]
Result: FAILURE :sunglasses: Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/269/

**Review by qe-tigergraph — COMMENTED** [review]
Result: FAILURE :sunglasses: Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/270/

**Review by billshitg — APPROVED** [review]

**Review by qe-tigergraph — COMMENTED** [review]
Result: FAILURE :sunglasses: Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/272/

**Review by qe-tigergraph — COMMENTED** [review]
Result: FAILURE :sunglasses: Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/275/

**Pull request merged**
