### PR TITLE
GML-1076: Distributed data loader group

### PR DESCRIPTION
**Pull request by billshitg**

### CODE REVIEW

**Review by parkererickson-tg — APPROVED** [review]

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/731/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/738/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/740/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/743/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Pull request merged**
