### PR TITLE
GML-1252: reinstall queries for the dataloaders by force

### PR DESCRIPTION
**Pull request by billshitg**

### CODE REVIEW

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/757/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Comment by parkererickson-tg** [comment]
Do we want to include a parameter in the factory functions/initialization of the dataloader to reinstall automatically on instantiation?

**Comment by billshitg** [comment]
> Do we want to include a parameter in the factory functions/initialization of the dataloader to reinstall automatically on instantiation?

Good idea. Added to the factory functions.

**Review by parkererickson-tg — APPROVED** [review]

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/759/

**Pull request merged**
