### PR TITLE
GML-1312: fix(install_query_file): match error string

### PR DESCRIPTION
**Pull request by billshitg**

### CODE REVIEW

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/834/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/835/

**Review by parkererickson-tg — APPROVED** [review]

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/838/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Pull request merged**
