### PR TITLE
fix(nodepiece): handle edge type empty list

### PR DESCRIPTION
**Pull request by parkererickson-tg**

### CODE REVIEW

**Review by billshitg — APPROVED** [review]

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/504/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/505/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Pull request merged**
