### PR TITLE
Kafka auth

### PR DESCRIPTION
**Pull request by tg-bill**
Code change:
* Add sasl_plaintext and sasl_ssl authentication for kafka

Testing:
* Unit tests added
* Unit tests passed

### CODE REVIEW

**Review by parkererickson — APPROVED** [review]
Looks good. I wonder if we want to add an `configureKafka()` method that takes in all of the kafka parameters and saves them in the GDS class. That way users won't have to fill in the creds/address/other info every time they define a dataloader.

**Comment by tg-bill** [comment]
yes, I was desperately hoping for such a function while modify the code:) Given we are 10 days till launch, let's pick it up after the launch, unless someone wants to do it now.

**Comment by parkererickson** [comment]
Holy cow... didn't put it together we are 10 days out. I could possibly do it tomorrow, it can't be *too* bad, right?

**Comment by tg-bill** [comment]
lol, time flies. Yeah, it should be like half-a-day of work? If you have the bandwidth that would be great.

**Comment by parkererickson** [comment]
Will do, I am sorta blocked on the cloud deployment stuff for now so I will take a look.

**Comment by tg-bill** [comment]
Cool. Thanks!

**Comment by tg-bill** [comment]
The kafka config looks good to me. However, I was thinking about the opposite: the global config as default and users can use the individual factory functions to override the default. But either way works and the second would take more effort. If nothing else I think we are ready to push it after Lenny looks at the docs. Thoughts?

**Comment by parkererickson** [comment]
Lenny is out on PTO this week, added @a-m-thomas for the doc review. I agree that the other way around would be nice but it is more difficult to implement. Possibly a future enhancement if we get enough requests for it.

**Review by a-m-thomas — APPROVED** [review]
Please capitalize all instances of "Kafka" in the docs for consistency. Looks good to me!

**Comment by parkererickson** [comment]
I also originally thought the override of global would be nice but realized it is tougher to implement. I believe Lenny is on PTO right now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
