### PR TITLE
fix(oo schema creation): primary id as attribute fix

### PR DESCRIPTION
**Pull request by parkererickson-tg**

### CODE REVIEW

**Review by billshitg — APPROVED** [review]

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/1021/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/1023/

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/1026/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Pull request merged**
