### PR TITLE
fix(ssl cert): fix how custom certs are handled

### PR DESCRIPTION
**Pull request by parkererickson-tg**

### CODE REVIEW

**Review by billshitg — APPROVED** [review]

**Comment by zhixiany** [comment]
@parkererickson-tg  can you also add a check here, if res["error"] key error, print res directly to see whole error

https://github.com/tigergraph/pyTigerGraph/blob/master/pyTigerGraph/pyTigerGraphAuth.py#L257

**Comment by parkererickson-tg** [comment]
Yeah. I am curious as to why we aren't using the built-in functions for requests over the `requests.request()` call. The built-in ones have more robust error messaging now. Will open a ticket to look into it further. Since it isn't directly related to the fix, I will put it in a different PR.

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/448/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Pull request merged**
