### PR TITLE
fix(featurizer): handle master and unpublished db version

### PR DESCRIPTION
**Pull request by billshitg**

### CODE REVIEW

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/484/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/485/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by trisjtg — APPROVED** [review]

**Pull request merged**
