### PR TITLE
GML-1090: HGTLoader

### PR DESCRIPTION
**Pull request by billshitg**

### CODE REVIEW

**Comment by billshitg** [comment]
> 

Epic catch! Thanks

**Review by parkererickson-tg — APPROVED** [review]

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/578/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/579/

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SKIPPED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/580/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by parkererickson-tg — APPROVED** [review]

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/582/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Pull request merged**
