### PR TITLE
GML-1273: Error handling for BigQuery uses

### PR DESCRIPTION
**Pull request by billshitg**
Temporary solution for handling error in GSQL commands for BigQuery uses, including, schema creation, data source creation, and loading job creating and running.

### CODE REVIEW

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/819/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/821/

**Review by parkererickson-tg — APPROVED** [review]

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/825/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Pull request merged**
